// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagmentSystem.Data;

#nullable disable

namespace StudentManagmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819073153_AddUniqueMobileNumber")]
    partial class AddUniqueMobileNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagmentSystem.Models.AcademicProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DurationYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalSemesters")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgramId");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "ProgramName")
                        .IsUnique();

                    b.ToTable("Program", t =>
                        {
                            t.HasCheckConstraint("CK_Program_DurationYears", "[DurationYears] > 0");

                            t.HasCheckConstraint("CK_Program_TotalSemesters", "[TotalSemesters] > 0");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearId"));

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcademicYearId");

                    b.ToTable("AcademicYear");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<decimal>("AttendancePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ClassesAttended")
                        .HasColumnType("int");

                    b.Property<int>("ClassesHeld")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentSemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SemesterSubjectId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentSemesterId", "SemesterSubjectId")
                        .IsUnique();

                    b.ToTable("Attendances", t =>
                        {
                            t.HasCheckConstraint("CK_Attendance_Classes", "[ClassesHeld] >= 0 AND [ClassesAttended] >= 0 AND [ClassesAttended] <= [ClassesHeld]");

                            t.HasCheckConstraint("CK_Attendance_Percentage", "[AttendancePercentage] >= 0 AND [AttendancePercentage] <= 100");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceRecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentSemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceRecordId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentSemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SessionId", "StudentSemesterId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ClassSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("FacultyId", "SessionDate");

                    b.HasIndex("SemesterSubjectId", "SessionDate");

                    b.ToTable("ClassSession");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FacultyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.FacultySubject", b =>
                {
                    b.Property<int>("FacultySubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultySubjectId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FacultySubjectId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SemesterSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("FacultyId", "SemesterSubjectId", "AcademicYearId")
                        .IsUnique();

                    b.ToTable("FacultySubjects");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GradePoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinMarks")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SemesterSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Materials", t =>
                        {
                            t.HasCheckConstraint("CK_Material_FileSize", "[FileSize] > 0");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("SemesterId", "ProgramId");

                    b.ToTable("Project", t =>
                        {
                            t.HasCheckConstraint("CK_Project_DateRange", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ProjectAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AllocationId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ProjectId", "StudentId")
                        .IsUnique();

                    b.ToTable("ProjectAllocations", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectAllocation_FinalScore", "[FinalScore] IS NULL OR ([FinalScore] >= 0 AND [FinalScore] <= 100)");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ProjectTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<decimal>("AssignedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EarnedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FacultyRemarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProjectAllocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentRemarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProjectAllocationId", "TaskStatus");

                    b.ToTable("Task", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectTask_CompletedDate", "[CompletedDate] IS NULL OR [CompletedDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_ProjectTask_DateRange", "[DueDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_ProjectTask_Scores", "[AssignedScore] >= 0 AND [EarnedScore] >= 0 AND [EarnedScore] <= [AssignedScore]");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SemesterId");

                    b.HasIndex("SemesterName")
                        .IsUnique();

                    b.HasIndex("SemesterNumber")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterResult", b =>
                {
                    b.Property<int>("SemesterResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EarnedCredits")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SGPA")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("StudentSemesterId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SemesterResultId");

                    b.HasIndex("StudentSemesterId")
                        .IsUnique();

                    b.ToTable("SemesterResults", t =>
                        {
                            t.HasCheckConstraint("CK_SemesterResult_Credits", "[EarnedCredits] >= 0 AND [EarnedCredits] <= [TotalCredits]");

                            t.HasCheckConstraint("CK_SemesterResult_SGPA", "[SGPA] >= 0 AND [SGPA] <= 10");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterSubject", b =>
                {
                    b.Property<int>("SemesterSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterSubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credits")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SemesterSubjectId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ProgramId", "SemesterId");

                    b.HasIndex("ProgramId", "SemesterId", "SubjectId")
                        .IsUnique();

                    b.ToTable("SemesterSubjects", t =>
                        {
                            t.HasCheckConstraint("CK_SemesterSubject_Credits", "[Credits] > 0");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSemesterId")
                        .HasColumnType("int");

                    b.Property<string>("EnrollmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("CurrentSemesterId");

                    b.HasIndex("EnrollmentNumber")
                        .IsUnique();

                    b.HasIndex("ProgramId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.StudentSemester", b =>
                {
                    b.Property<int>("StudentSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSemesterId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentSemesterId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId", "SemesterId", "AcademicYearId")
                        .IsUnique();

                    b.ToTable("StudentSemesters");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubjectId");

                    b.HasIndex("SubjectCode")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SubjectResult", b =>
                {
                    b.Property<int>("SubjectResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditsEarned")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ExternalMarks")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("InternalMarks")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PracticalMarks")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SemesterResultId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMarks")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubjectResultId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SemesterResultId");

                    b.HasIndex("SemesterSubjectId");

                    b.HasIndex("SemesterResultId", "SemesterSubjectId")
                        .IsUnique();

                    b.ToTable("SubjectResults", t =>
                        {
                            t.HasCheckConstraint("CK_SubjectResult_CreditsEarned", "[CreditsEarned] >= 0");

                            t.HasCheckConstraint("CK_SubjectResult_Marks", "[InternalMarks] >= 0 AND [ExternalMarks] >= 0 AND [PracticalMarks] >= 0 AND [TotalMarks] >= 0");
                        });
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActivate")
                        .HasColumnType("bit");

                    b.Property<string>("Mobilenumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobilenumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AcademicProgram", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Department", "Department")
                        .WithMany("Programs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Attendance", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Semester", null)
                        .WithMany("Attendances")
                        .HasForeignKey("SemesterId");

                    b.HasOne("StudentManagmentSystem.Models.SemesterSubject", "SemesterSubject")
                        .WithMany("Attendances")
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Student", null)
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId");

                    b.HasOne("StudentManagmentSystem.Models.StudentSemester", "StudentSemester")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Subject", null)
                        .WithMany("Attendances")
                        .HasForeignKey("SubjectId");

                    b.Navigation("SemesterSubject");

                    b.Navigation("StudentSemester");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AttendanceRecord", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Faculty", null)
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("FacultyId");

                    b.HasOne("StudentManagmentSystem.Models.ClassSession", "Session")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Student", null)
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId");

                    b.HasOne("StudentManagmentSystem.Models.StudentSemester", "StudentSemester")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Subject", null)
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Session");

                    b.Navigation("StudentSemester");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ClassSession", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.SemesterSubject", "SemesterSubject")
                        .WithMany("ClassSessions")
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("SemesterSubject");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Faculty", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Department", "Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.User", "User")
                        .WithOne("Faculty")
                        .HasForeignKey("StudentManagmentSystem.Models.Faculty", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.FacultySubject", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.AcademicYear", "AcademicYear")
                        .WithMany("FacultySubjects")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Faculty", "Faculty")
                        .WithMany("FacultySubjects")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Semester", null)
                        .WithMany("FacultySubjects")
                        .HasForeignKey("SemesterId");

                    b.HasOne("StudentManagmentSystem.Models.SemesterSubject", "SemesterSubject")
                        .WithMany("FacultySubjects")
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Subject", null)
                        .WithMany("FacultySubjects")
                        .HasForeignKey("SubjectId");

                    b.Navigation("AcademicYear");

                    b.Navigation("Faculty");

                    b.Navigation("SemesterSubject");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Material", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Semester", null)
                        .WithMany("Materials")
                        .HasForeignKey("SemesterId");

                    b.HasOne("StudentManagmentSystem.Models.SemesterSubject", "SemesterSubject")
                        .WithMany("Materials")
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Subject", null)
                        .WithMany("Materials")
                        .HasForeignKey("SubjectId");

                    b.HasOne("StudentManagmentSystem.Models.User", "UploadedByUser")
                        .WithMany("UploadedMaterials")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemesterSubject");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Project", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.AcademicProgram", "AcademicProgram")
                        .WithMany("Projects")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Semester", "Semester")
                        .WithMany("Projects")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ProjectAllocation", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Faculty", "Faculty")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Project", "Project")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Student", "Student")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ProjectTask", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.ProjectAllocation", "ProjectAllocation")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectAllocation");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterResult", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.StudentSemester", "StudentSemester")
                        .WithOne("SemesterResult")
                        .HasForeignKey("StudentManagmentSystem.Models.SemesterResult", "StudentSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSemester");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterSubject", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.AcademicProgram", "AcademicProgram")
                        .WithMany("SemesterSubjects")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Semester", "Semester")
                        .WithMany("SemesterSubjects")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Subject", "Subject")
                        .WithMany("SemesterSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Student", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Semester", "CurrentSemester")
                        .WithMany()
                        .HasForeignKey("CurrentSemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.AcademicProgram", "AcademicProgram")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Semester", null)
                        .WithMany("StudentsAsCurrentSemester")
                        .HasForeignKey("SemesterId");

                    b.HasOne("StudentManagmentSystem.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("StudentManagmentSystem.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("CurrentSemester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.StudentSemester", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Semester", "Semester")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.Student", "Student")
                        .WithMany("StudentSemesters")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SubjectResult", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Grade", "Grade")
                        .WithMany("SubjectResults")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.SemesterResult", "SemesterResult")
                        .WithMany("SubjectResults")
                        .HasForeignKey("SemesterResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagmentSystem.Models.SemesterSubject", "SemesterSubject")
                        .WithMany("SubjectResults")
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("SemesterResult");

                    b.Navigation("SemesterSubject");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.User", b =>
                {
                    b.HasOne("StudentManagmentSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AcademicProgram", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("SemesterSubjects");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.AcademicYear", b =>
                {
                    b.Navigation("FacultySubjects");

                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ClassSession", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Department", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Faculty", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("FacultySubjects");

                    b.Navigation("ProjectAllocations");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Grade", b =>
                {
                    b.Navigation("SubjectResults");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Project", b =>
                {
                    b.Navigation("ProjectAllocations");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.ProjectAllocation", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Semester", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("FacultySubjects");

                    b.Navigation("Materials");

                    b.Navigation("Projects");

                    b.Navigation("SemesterSubjects");

                    b.Navigation("StudentSemesters");

                    b.Navigation("StudentsAsCurrentSemester");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterResult", b =>
                {
                    b.Navigation("SubjectResults");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.SemesterSubject", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClassSessions");

                    b.Navigation("FacultySubjects");

                    b.Navigation("Materials");

                    b.Navigation("SubjectResults");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Attendances");

                    b.Navigation("ProjectAllocations");

                    b.Navigation("StudentSemesters");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.StudentSemester", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Attendances");

                    b.Navigation("SemesterResult");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.Subject", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Attendances");

                    b.Navigation("FacultySubjects");

                    b.Navigation("Materials");

                    b.Navigation("SemesterSubjects");
                });

            modelBuilder.Entity("StudentManagmentSystem.Models.User", b =>
                {
                    b.Navigation("Faculty");

                    b.Navigation("Student");

                    b.Navigation("UploadedMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
